services:
  backend:
    image: melosystem/store-dashboard-backend:v3
    container_name: store_dashboard_backend
    restart: always
    env_file:
      - .env
  frontend:
    image: melosystem/store-dashboard-frontend:v3
    container_name: store_dashboard_frontend
    ports:
      - "8080:80"
    restart: always
