// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables with fallbacks
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://cbpemxjuwkjcbgcznzvb.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicGVteGp1d2tqY2JnY3puenZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTEwNDEsImV4cCI6MjA3MDE2NzA0MX0.ag9wFrwfyudYgLhgrPg5PrkfOavYxx7kshFR1uUeRBc";

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('Supabase environment variables not found. Using fallback values.');
}

// Create Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export for use in other parts of the application
export default supabase;