// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbpemxjuwkjcbgcznzvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicGVteGp1d2tqY2JnY3puenZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTEwNDEsImV4cCI6MjA3MDE2NzA0MX0.ag9wFrwfyudYgLhgrPg5PrkfOavYxx7kshFR1uUeRBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});